# Generated by Django 5.1.6 on 2025-04-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.productstatus', verbose_name='status'),
        ),
    ]
