# Generated by Django 4.1 on 2023-03-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='bbb'),
        ),
    ]
