# Generated by Django 4.1 on 2023-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../static/accounts/images/defult_prof.jpg', upload_to=''),
        ),
    ]
