# Generated by Django 4.1 on 2023-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_pass_token',
            field=models.CharField(default='xxxxxxxxxxxxxxxxxxxx', max_length=20),
            preserve_default=False,
        ),
    ]
