# Generated by Django 4.1 on 2023-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_status'),
        ('accounts', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='products.product'),
        ),
    ]
