# Generated by Django 4.1 on 2023-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='d', max_length=1),
        ),
    ]
