# Generated by Django 4.1 on 2023-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='d', max_length=1),
        ),
    ]
